version: '3.1'

services:
  fast_api:
    container_name: fast_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api/db/main_db:/api/db/main_db
    ports:
      - "5005:5005"
